### ISSUE TITLE
Getting a list via ARCL

### ISSUE THREAD

**Issue by jonathanleinola** [OmronAPAC/Omron_AMR_ROS2#3]
Hi,

any ideas on how to get a list of outputs from command outputList via ARCL?

Kindly,
Jonathan

**Comment by CFZeon** [comment]
Hi Jonathan,

I am not quite sure of what your question means. Are you looking to store the outputList in a Python List or do you want to just obtain the entire set of data that the outputList command prints out?

Regards,
Zeon

**Comment by CFZeon** [comment]
Hi Jonathan,

Following one of the Action Server / Service examples, you would want to assign to  line_identifier in the ArclApi service type, the string "End of OutputList". The command itself should be assigned "outputlist" as it is what you want to obtain from ARCL. 

Please tell me how it works for you.

Regards,
Zeon

**Comment by CFZeon** [comment]
Hi Jonathan, 

I will look into it when I can. Another solution i can think of is to modify execute_callback in action_server.py, found in om_aiv_navigation. In line 47,  there should be a self._result.res_msg = result.decode() which should contain what you are looking for when you use the action server and want the result back.

**Comment by jonathanleinola** [comment]
Hi Zeon, 

Great thanks! I did similarly as you, but currently, my test environment utilizes the older LD package. Therefore I can't test currently that script. But seems to be solved :)

Kindly,
Jonathan
